package-lock.json, package.json, src/controller/auth.js, src/lib/jwt.js, src/lib/sequelize.js, src/models/admin.js, src/routes/auth.js, src/services/auth/index.js
=> [P2-9] Admin login feature.

src/controller/auth.js, src/controller/user.js, src/index.js, src/middleware/authorizeLoginUser.js, src/routes/auth.js, src/routes/index.js, src/routes/user.js, src/services/auth/index.js, src/services/user/index.js
=> [P2-5] Login Feature

src/controller/user.js, src/index.js, src/middleware/authorizeLoginUser.js, src/routes/user.js, src/services/user/index.js
=> [P2-13] Edit Profile Feature

src/controller/product.js, src/routes/product.js, src/services/product/index.js
=> [P2-17] Created get all product end point

src/controller/auth.js, src/routes/auth.js, src/services/auth/index.js, src/templates/resetPassword.html
=> [P2-7] reset password

.gitignore, src/controller/admin.js, src/controller/index.js, src/index.js, src/routes/admin.js, src/routes/index.js, src/services/admin/index.js
=> AddProduct controller added

src/controller/admin.js, src/routes/admin.js, src/services/admin/index.js
=> [P2-40] See all product list (Admin)

src/services/product/index.js
=> [P2-20] FEAT: added sorting mechanism in getAllProduct end point

src/controller/admin.js, src/index.js, src/models/produk.js, src/models/stokStatus.js, src/routes/admin.js, src/routes/auth.js, src/routes/user.js, src/services/admin/index.js
=> [P2-37] Admin Add Product Feature

src/controller/product.js, src/lib/sequelize.js, src/services/product/index.js
=> [P2-19] Product Filter Feature. Added filter by product name and by category in getAllProduct end point.

src/controller/admin.js, src/routes/admin.js, src/services/admin/index.js
=> [P2-42] sort product list in admin

src/services/admin/index.js
=> [P2-41] filtering daftar product for admin

src/controller/admin.js, src/routes/admin.js, src/services/admin/index.js
=> [P2-38] Admin Edit Product Feature

src/controller/admin.js, src/routes/admin.js, src/services/admin/index.js
=> [P2-39] Admin Delete Product Feature

src/controller/cart.js, src/routes/cart.js, src/services/cart/index.js
=> [P2-8][P2-23][P2-24] cart and transaction protection

src/controller/admin.js, src/lib/sequelize.js, src/routes/admin.js, src/services/admin/index.js
=> [P2-44] Admin Get ProductStockHistory Feature

package-lock.json, package.json, src/controller/address.js, src/index.js, src/lib/axiosInstance.js, src/models/alamat.js, src/routes/address.js, src/routes/index.js, src/services/address/index.js
=> [P2-25] User's Address Feature. Fixed addNewAddress end point and added getOngkir end point

src/controller/auth.js, src/models/cart.js, src/models/user.js, src/routes/auth.js, src/services/auth/index.js
=> Feat: added login with google

src/controller/admin.js, src/models/daftarTransaksi.js, src/routes/admin.js, src/services/admin/index.js
=> [P2-35] Admin Serve User Custom Order Feature

src/controller/address.js, src/controller/cart.js, src/controller/transaction.js, src/routes/cart.js, src/routes/transaction.js, src/services/address/index.js, src/services/cart/index.js, src/services/transaction/index.js
=> FEAT: added paymentMethod end points

src/controller/transaction.js, src/lib/sequelize.js, src/routes/transaction.js, src/services/admin/index.js, src/services/transaction/index.js
=> [P2-27] User Upload Proof of Payment Feature

src/controller/index.js, src/controller/product.js, src/controller/report.js, src/index.js, src/lib/sequelize.js, src/models/userProduct.js, src/routes/index.js, src/routes/product.js, src/routes/report.js, src/services/product/index.js, src/services/report/index.js
=> [P2-46] Sales Report

src/controller/admin.js, src/routes/admin.js, src/services/admin/index.js, src/services/transaction/index.js
=> [P2-47] Admin Sales Revenue Feature

src/controller/transaction.js, src/lib/sequelize.js, src/services/transaction/index.js
=> [P2-31] [P2-32] [P2-33] Admin Transaction List Feature

src/controller/address.js, src/controller/product.js, src/lib/sequelize.js, src/routes/address.js, src/routes/product.js, src/services/address/index.js, src/services/admin/index.js, src/services/product/index.js, src/services/transaction/index.js
@hasianamin @theodevoid tolong di merge kk hkhkhk
=> Fix/Feat/UI: fix feature and UI

src/services/transaction/index.js
=> FIX: fixed bug in search by name filter in admin transaction list

src/services/admin/index.js
=> DELETED UNECESSARY LOGS

src/middleware/authorizeLoginAdmin.js, src/routes/auth.js
=> FIX: fix bug in refresh login admin

src/services/report/index.js
=> FIX: report date 
